
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: smart-property-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: property
      MYSQL_DATABASE: property_db
      MYSQL_USER: property
      MYSQL_PASSWORD: property
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart-property-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/property_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: property
      APP_ALLOWED_ORIGINS: http://localhost:80
      JWT_SECRET: change-me-in-prod
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smart-property-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
