# 本地开发配置，可通过 `--spring.profiles.active=local` 启用
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/property_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: your_mysql_username # TODO: 修改为本地 MySQL 用户名
    password: your_mysql_password # TODO: 修改为本地 MySQL 密码
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    time-zone: UTC

server:
  port: 8080

app:
  security:
    jwt:
      secret: change-me-in-local # TODO: 修改为本地使用的 JWT 密钥
      access-token-expiration-minutes: 30
      refresh-token-expiration-days: 7
    cors:
      allowed-origins: http://localhost:5173,http://localhost
